project:
  type: website
  output-dir: ../docs

website:
  title: "da_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Stan_Primer_Full.qmd
      - text: Lecture Notes
        menu:
          - href: lecture_notes/MCMC/MCMC.qmd
            text: MCMC
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-width: 8
    fig-height: 4
    code-fold: false
    code-tools: true
    
editor: visual


