project:
  type: website
  output-dir: ../docs

website:
  title: "da_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-width: 8
    fig-height: 4
    code-fold: true
    code-tools: true
    
editor: visual


